[project]
name = "dify_app"
version = "0.1.0"
description = "LLM apps for plant"
authors = [
    { name = "wp", email = "wpwupingwp@outlook.com" },
]
dependencies = ['biopython', 'quart', 'uvicorn', 'aiohttp',
    'torchmetrics', 'torch',
    'selenium', 'beautifulsoup4', 'certifi', 'urllib3',
    'loguru'
]
requires-python = ">=3.11.*"
readme = "README.md"
license = { text = "AGPL-3" }

[tool.pdm]
distribution = false
[project.script]
llm_server = 'uvicorn pubmed:app --port 2024'
crawler = 'python src/crawler.py'
